Section "InputClass"
  Identifier "Touchpad"
  Driver "libinput"
  MatchIsTouchpad "on"
  Option "Tapping" "on"
  Option "NaturalScrolling" "true"
  Option "AccelSpeed" "0.2"
  Option "ScrollPixelDistance" "35"
EndSection
