#!/bin/bash

#COLORS
greenColor="\e[1;32m"
redColor="\e[1;31m"
yellowColor="\e[1;33m"
blueColor="\e[1;34m"
defaultColor="\e[0m"
defaultColorBold="\e[1m"

# GLOBAL VARIABLES
URLS_FILE="/etc/checkprice/urls"

# CTRL+C
trap ctrl_c INT
function ctrl_c() {
	echo -e "\n\n${redColor}[*] ${defaultColor}Exiting...\n"
	exit 1;
}

function helpPanel() {
	echo -e "\n${yellowColor}[*]${defaultColor} Usage: checkprice [OPTION] [PRODUCT_NAME]"
	echo -e "\nIt will search through the urls of the product specified and show its price"
	echo -e "\nOPTIONS:
  -a                   Add a new product.
  -h                   Show this panel.
  -l                   List all the products saved.
  -r <PRODUCT_NAME>    Remove <PRODUCT_NAME> from the products saved.\n"
}

function removeProduct() {
	if [ "$(/bin/cat $URLS_FILE | grep -x "# $1")" == "" ]; then
		echo -e "\n${redColor}[-] ${defaultColor}No product found!\n"
		exit 1
	fi

	linesToRemove="$(/bin/cat $URLS_FILE | grep -A 2 "$1")"

	echo -e "$(/bin/cat $URLS_FILE | grep -vx "$linesToRemove")" > $URLS_FILE
	echo -e "\n${yellowColor}[+] ${defaultColor}Product '${defaultColorBold}$1${defaultColor}' removed\n"
	exit 0
}

function addProduct() {
	echo -en "\n${blueColor}->${defaultColor} Enter the product name: "
	read product_name
	echo -en "\n${blueColor}->${defaultColor} Enter the Zococity url: "
	read zococity_url
	echo -en "\n${blueColor}->${defaultColor} Enter the Amazon url: "
	read amazon_url

	echo "# $product_name" >> $URLS_FILE
	echo "Zococity: $zococity_url" >> $URLS_FILE
	echo "Amazon: $amazon_url" >> $URLS_FILE

	echo -e "\n${greenColor}[+]${defaultColor} New product added!\n"

	exit 0
}

function showProducts() {
	i=0
	while read line; do
		if [ $(($i % 3)) -eq 0 ]; then
			echo -e "\n${blueColor}-> $(echo $line | cut -c 3-)${defaultColor}"
		else 
			echo -e "  ${yellowColor}·${defaultColor} $line"
		fi

		let i++
	done < $URLS_FILE

	echo ""
	exit 0
}


function checkPrice() {
	productName=$(/bin/cat $URLS_FILE | grep -i "$1" | grep '#' | cut -c 3-)

	if [ "$productName" == "" ]; then
		echo -e "\n${redColor}[-] ${defaultColor}No product found!\n"
		exit 1
	fi

	echo -e "\n${defaultColorBold}-> ${yellowColor}$productName${defaultColor}\n"
	zococity_url=$(/bin/cat $URLS_FILE | grep -i -A 2 "$1" | grep "Zococity" | sed 's/Zococity: //')
	amazon_url=$(/bin/cat $URLS_FILE | grep -i -A 2 "$1" | grep "Amazon" | sed 's/Amazon: //')

	checkZococityPrice $zococity_url
	# checkAmazonPrice $amazon_url
}

function checkZococityPrice() {
	prices=$(curl -s $1 | grep "price-item" -A 1 | grep "€" | tr -d " ")

	i=0
	for price in $prices; do
		finalPrice=$(echo $price | tr -d '€' | sed 's/,/./')

		if [ $i == 0 ]; then 
			cheapPrice=$finalPrice
			let i++
		else
			if [ $(echo "$finalPrice < $cheapPrice" | bc -l) ]; then
				cheapPrice=$finalPrice
			fi
		fi
	done

	echo -e "    Zococity: ${greenColor}$cheapPrice€${defaultColor}"
}

function checkAmazonPrice() {
	price=$(curl -s $1 | grep "priceblock_ourprice" -A 1)
	echo $price
}

function checkAllPrices() {
	j=0
	echo -e "\n${greenColor}[+]${defaultColor} Checking all prices..."
	while read line; do
		if [ $(($j % 3)) == 0 ]; then
			checkPrice "$(echo $line | cut -c 3-)"
		fi

		let j++
	done < $URLS_FILE
}

while getopts "alhr:" option; do
	case "$option" in
		a) addProduct;;
		r) removeProduct "$OPTARG";;
		l) showProducts;;
		*) helpPanel; exit 1;;
	esac
done

if [ "$1" == "" ]; then
	checkAllPrices
else
	checkPrice "$1"
fi

echo ""
exit 0
